version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

    groups:
      gatsby:
        patterns:
          - "gatsby"
          - "gatsby-*"
      dependencies:
        update-types:
          - "patch"
          - "minor"
