name: Build
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          yarn install
          yarn cypress install
          yarn cypress verify
      - name: Test
        run: yarn test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    container: node:14
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          production-branch: master
          publish-dir: "./public"
          deploy-message: "Deploy from GitHub Actions"
          netlify-config-path: ./netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}