name: PR build
on: pull_request

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - name: Install dependencies
        run: npm ci
      - name: Type check
        run: npm run type-check
      - name: ESLint
        run: npm run lint
      - name: Prettier
        run: npm run prettier
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.13.0
      - name: Install dependencies
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: "http://[::1]:8000/"
